- src/utils.ts
- test/to-export.test.ts
When exports happen to include the file extension ( resolved from dirs / explicitly written ), generation is completed without stripping the extension.
This PR reapplies a change made in nuxt/framework#3540
> fix: strip file extensions for exports

- README.md
It seems like the last yarn command `yarn install unimport` has been replaced,instead we have to use `yarn add unimport`
> fix: updating yarn command

- src/utils.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/template-literal.ts
Hey there!  I was running into a funky edge case with regexes and string template literals.  Thought I'd contribute a test for it and a really simple fix.
Because string template literals can span multiple lines, unbalanced backticks in the regex literal try to match into the subsequent lines.  Because the string template RE doesn't include a `\n`, any symbols between the regex and the next backtick aren't picked up by the library.  Simple fix is to move the regex processor up so we clear out any unbalanced quote marks in advance.
Here's a regexr to demonstrate: https://regexr.com/6mce0
Awesome work on this tool, let me know if there's anything I can help with.
> fix: regexes break with unbalanced backticks

- src/utils.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/template-literal.ts
Fixes #49
1.) added `` ` `` to `quotesRE[0]` to support cases like `` const x = `"${ref()}"` ``
2.) made `templateLiteralRE` recursive to support cases with nested template literals (`` const x = `prefix1${`prefix2${ref()}`}` ``)
3.) made `templateLiteralRE` multiline (added `\r` and `\n`)
> fix: nested quotes in template string, multiline template string (#49)

- playground/src/App.vue
- src/addons/vue-template.ts
- test/vue-template.test.ts
Solve the caveat mentioned in https://github.com/unjs/unimport/pull/15
Requiring adding `.value` was verbose and obeyed the direction for Vue to have reactivity transform. With this PR, auto imports in vue template are now auto unref, making it works just like in `<script setup>`. The caveat then becomes that you can't assign to auto imported ref, which we had correct types to cover it (readonly).
> feat(vue-template)!: auto unwrap refs

- src/scan-dirs.ts
- src/types.ts
close https://github.com/antfu/unplugin-auto-import/issues/222
> feat(dir)!: support glob pattern in `dirs`

- playground/composables/nested/index.ts
- playground/src/App.vue
- playground/vite.config.ts
- src/scan-dirs.ts
- src/types.ts
- test/scan-dirs.test.ts
This will be a breaking change for Nuxt, while leading providing a new option to customize the patterns and bring back the old behavior if needed.
> feat(scan): options for custom `filePatterns`, remove nested glob by default

- src/context.ts
- src/utils.ts
RegExp performance issue found by @pi0 in some nice debugging. (We are trimming whitespace anyway so doesn't make any difference to our usage.)
Also refactored Array.from -> `for/of` which might also slightly improve performance with very large strings by using an iterator.
> perf: decrease processing time for exclude regexp

- src/utils.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/existing8.ts
Using `export` before `import default` cannot remove defined values
origin code
```ts
// file specifier
import { bar } from 'specifier2'
export { bar }
import foo from 'specifier1'
export { foo }
```
No need for auto import at this point, but output:
```ts
// file specifier
import { foo } from 'specifier'   // auto import 
import { bar } from 'specifier2'
export { bar }
import foo from 'specifier1' // error
export { foo }
```
> fix: cannot remove defined values

- src/addons/vue-template.ts
- test/vue-template.test.ts
Fix https://github.com/antfu/unplugin-auto-import/issues/263.
Currently will occur type errors when `ComponentCustomProperties` under `@vue/runtime-core`, I think we should follow the [Vue documentation](https://vuejs.org/api/utility-types.html#componentcustomproperties) to define it.
> fix: vue template ComponentCustomProperties interface

- README.md
I suspect the README examples weren't quite right. Feel free to close this PR if I'm mistaken!
> docs: use "presets" key instead of "imports" where needed

- playground/src/App.vue
- playground/src/Options.vue
- playground/src/Setup.vue
- src/addons/vue-template.ts
- test/vue-template.test.ts
fix https://github.com/nuxt/nuxt/issues/15594
fix https://github.com/unjs/unimport/issues/192
This could be a potential breaking change (but expected behavior).
This only applies to SFC using Options API, where user-defined local data uses the same name as the auto-import entry. This PR makes it use the local data over auto-imported whenever possible.
The alternative solution is to enable template auto import only for `<script setup>`. but I consider that would be less intuitive and bigger breaking change.
> fix(vue-template)!: prioritize local variable over auto import

- playground/package.json
- playground/src/Options.vue
- playground/src/Setup.vue
- playground/tsconfig.json
- pnpm-lock.yaml
- src/context.ts
- src/global.ts
- src/preset.ts
- src/presets/vue.ts
- src/types.ts
- src/utils.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/dts.test.ts
- test/fixtures.test.ts
- test/fixtures/no-type.ts
Resolve https://github.com/nuxt/nuxt/issues/12808#issuecomment-1420406745
Resolve https://github.com/antfu/unplugin-auto-import/issues/61
It seems to work with my TypeScript v4.9.5, not even requiring 5.0.
> feat: types auto import

- src/presets/vue.ts
close #265 
Though computed can return ComputedRef and WritableComputedRef, I'd expect those two to be apreset return type as well. Therefore I added WritableComputedRef to preset types
> feat: added WritableComputedRef to preset types for vuejs auto import

- playground/composables/index.ts
- playground/composables/nested/bar/sub/index.ts
- src/context.ts
- src/scan-dirs.ts
- src/types.ts
- test/dts.test.ts
- test/scan-dirs.test.ts
fix https://github.com/unplugin/unplugin-auto-import/issues/422#issuecomment-1704735457
fix https://github.com/nuxt/nuxt/issues/19467
> feat: support scanning types export under `dirs`

- src/utils.ts
- test/dedupe.test.ts
n/a
This should improve DX as it allows to quickly identify a duplicated import.
> feat(utils): name used import on duplicate on warning

- src/context.ts
- test/inject.test.ts
related: https://github.com/unplugin/unplugin-auto-import/issues/279
Deep ternary operators were omitted during auto importing causing incomplete imports.
Cases like `const result = true ? false ? A : B : C` resulted in missing `B` import, as it was treated as object property.
This fix checks if the current element is preceded with `:`, so it's not the object property and should not be removed from mapping.
> fix: support deep ternary injection

- src/utils.ts
- test/to-export.test.ts
#290
This resolves issue #290 by allowing package names with `.` in the name to be left unchanged.
This change alters the regex used to match the extension to ensure that it only changes the last segment of the path and when no preceeding `/` or `./` is present in the segment then do not alter the path.
I include some outputs of the testing I have done with this Regex in my browser console.
I do not believe this will be a breaking change as the only change in behaviour here, I believe, is to ensure that only the extension is dropped other segments of the path are unchanged.
> fix: toExports extension strip

- src/node/scan-dirs.ts
Fixes #350 
Might break previous behavior if previously users had these files next to each other: `file.ts`, `file.ts.ts`, but I think that's unlikely. 
Will correctly handle cases like `user.model` when `user.model.ts` file exists.
Will not break `user-model.ts` cases because `user-model.ts.ts` files are unlikely to exist in codebases.
> fix: change scanning of multi-part filenames (#350)

- src/node/scan-dirs.ts
resolves #353
There is a file `/path/exports.ts` with the following export: `export * from 'axios'`. The expected behavior is to automatically export all named and default exports from the axios module. However, the original behavior did not treat axios as a module and instead attempted to resolve it as `/path/axios.ts` or other files with various extensions.
This PR fixes the issue.
> fix: correct path handling for * exports in `scanExports` when exporting from module

- src/node/scan-dirs.ts
PR #354 fixed the module import resolution issue, but it did not consider Windows systems. On Windows, serious errors occur due to the use of `\`.
This PR fixes the issue by standardizing path separators to `/` after determining the module path.
> fix: resolve module path conversion issue in scanExports on Windows

- src/addons/vue-template.ts
- src/preset.ts
[https://stackblitz.com/edit/unimport-360](https://stackblitz.com/edit/unimport-360?file=vite.config.ts,auto-imports.d.ts&terminal=dev)
配置 `ignoreDts` 后，Vue Template 类型声明中依然存在，在 [`fa4589f`](https://github.com/unjs/unimport/pull/360/commits/fa4589f44f9e21e777c83212c27cb35050030419) 修复
使用 [vitesse-webext](https://github.com/antfu-collective/vitesse-webext) 开发插件时遇到的问题
**原本的写法** 是这样
```
// plugins:
AutoImport({
imports: [
{
'webextension-polyfill': [
['*', 'browser'],
],
},
]
})
```
---
但我在 `Options.vue`、`Popup.vue` 等页面中使用
```
browser.runtime.getURL('assets/logo.svg')
```
会报错 `TypeError: Cannot read properties of undefined (reading 'getURL')`
`browser` 虽然在编辑器中的类型是对的，但问题是实际导入后会变成
```
{
default: Module
}
```
---
**修改后** 变成 `default as browser`，问题解决了
```
// plugins:
AutoImport({
imports: [
{ …
```
> fix: dtsDisabled option is not working

- src/addons/vue-template.ts
- test/vue-template.test.ts
> fix: drop `declare module '@vue/runtime-core'`

- src/presets/vue.ts
vue3.4: useModel vue3.5: useId, onWatcherCleanup, useTemplateRef
> feat: Update vue.ts, add vue3.4 3.5 api

- src/utils.ts
- test/star-type-import.test.ts
**Description**:  
This PR introduces support for wildcard (`*`) type exports. With this change, `unimport` now can generate `export type * as` syntax.
**Issue Reference**:  
This PR resolves #378
- **Support for `export type * as`**:  
`toTypeReExports` function now handles wildcard type exports differently, generating `export type * as Foo` instead of `export type { default as Foo }`.
- **Refactor for modularity**:  
A new helper function, `makeTypeModulesMap`, was added to organize both wildcard and named type imports for easier processing.
- **Breaking Change**:  
If you previously used `name: '*'` to generate `export type { default as Foo }`, update your config to `name: 'default'` for the same behavior. Wildcard imports now generate `export type * as Foo`.
To maintain the behavior …
> feat: support `export type * as` syntax

- README.md
- package.json
- playground/composables/nested/index.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/context.ts
- src/node/scan-dirs.ts
- src/types.ts
- src/utils.ts
- test/dts.test.ts
- test/public-api.test.ts
- test/scan-dirs.test.ts
Support exclude glob syntax([refrence](https://github.com/unplugin/unplugin-auto-import/pull/392)), like:
```ts
dirs: [
'./composables/**/*', 
'!./composables/nested**/*'
]
```
Support set some dir scanning exclude types([refrence](https://github.com/unplugin/unplugin-auto-import/pull/544)), like:
```ts
dirs: [
'./composables/**/*',
{ 
glob: './composables/nested**/*', 
types: false 
}
]
```
> feat(scan-dirs): support exclude glob and set dirs exclude types

- src/node/scan-dirs.ts
- src/types.ts
> fix(scan-dirs): add `tsx` and `jsx` into default file extensions

- src/utils.ts
- test/to-imports.test.ts
resolves https://github.com/atinux/nuxt-auth-utils/issues/191
this ensures we normalise `.d.ts` to `.js` and the same for `.d.mts` and `.d.cts`
> fix: normalise `.d.ts` file extensions

- src/node/scan-dirs.ts
- test/scan-dirs.test.ts
> fix(scan-dirs): retain the original `dirs` glob scanning

- package.json
Check https://arethetypeswrong.github.io/?p=unimport%403.14.5 , node 16 from CJS masquerading as ESM
> build: update exports

- src/addons/vue-directives.ts
- test/vue-directives.test.ts
We're removing the `resolveDirective` from the Vue static import and we need to remove it only when there are no more directives, the user may be using missing directives or globally registered directives.
Added a test used for coverage (`v-missing`  directive), checking it is still there:
`import { resolveDirective as _resolveDirective, ... } from 'vue'`
> fix(vue-directives): remove `resolveDirective` import when needed

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/unplugin.ts
replace `@rollup/pluginutils` with `unplugin-utils`
- 🌍 Platform agnostic, supports running in the browser, Node.js... (Replace `node:path` with `pathe`)
- ✂️ Subset, smaller bundle size.
See more https://github.com/sxzz/unplugin-utils
https://npmgraph.js.org/?q=unplugin-utils,@rollup/pluginutils
> refactor: replace `@rollup/pluginutils` with `unplugin-utils`

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/node/scan-dirs.ts
Tested with nuxt and confirmed to work in https://github.com/nuxt/nuxt/issues/30137#issuecomment-2664169761
Revert "fix: revert #396, move back to `fast-glob`"
This reverts commit 7bc76c5f87e2ca9b52062d21fa0dd20381e378cb.
> feat: switch to tinyglobby 0.2.11 addressing previous performance issues

- src/node/extract-package.ts
resolves #441
pkg-types v2 is ESM-only while unimport v4 is dual format.
> fix: dynamically import pkg-types v2 for cjs compat

- src/addons/vue-directives.ts
Check if the directive matches the name before removing the `v-` prefix.
**NOTE**: this should be ported to `v4`.
Testing Vuetify directives with its own unimport preset, we allow prefixing the directives to avoid collisions with third-party libs:
- `v-click-outside` is the directive => `ClickOutside` from `vuetify/directives`
- or `v-vuetify-click-outside` when prefixing (`as: 'VuetifyClickOutside'`)
_prefix vuetify directives error_
> fix(vue-directives): check directive name before removing `v-` prefix

- src/types.ts
This PR updates the `ScanDirExportsOptions.filePatterns` to include `.tsx` and `.jsx` in the default value desc.
> docs: update filePatterns default desc to include .tsx/.jsx

- src/presets/vue.ts
This PR adds Vue APIs `getCurrentWatcher`, `isShallow`, and `ShallowRef` to Vue preset
> feat: add new vue api in presets

- src/addons/vue-template.ts
- src/utils.ts
- test/addon-extend-imports.test.ts
- test/addon-inject-hooks.test.ts
- test/dts.test.ts
- test/vue-directives.test.ts
- test/vue-template.test.ts
Before:
```ts
declare global {
...
const reactive: typeof import('vue')['reactive']
const readonly: typeof import('vue')['readonly']
const ref: typeof import('vue')['ref']
const resolveComponent: typeof import('vue')['resolveComponent']
const shallowReactive: typeof import('vue')['shallowReactive']
const shallowReadonly: typeof import('vue')['shallowReadonly']
const shallowRef: typeof import('vue')['shallowRef']
const toRaw: typeof import('vue')['toRaw']
const toRef: typeof import('vue')['toRef']
const toRefs: typeof import('vue')['toRefs']
const toValue: typeof import('vue')['toValue']
const triggerRef: typeof import('vue')['triggerRef']
const unref: typeof import('vue')['unref']
...
}
```
After:
```ts
declare global {
...
const { reactive, readonly, ref, resolveComponent, …
```
> feat: optimize type declaration generation with `const { ... }`

- src/preset.ts
- test/dts.test.ts
resolves #470
Add missing [commonPresets](https://github.com/unjs/unimport/blob/v5.4.0/src/preset.ts#L10) property keys (see [ImportCommon](https://github.com/unjs/unimport/blob/main/src/types.ts#L8)).
> fix(presets): prevent `resolvePreset` from omitting `typeFrom`
